### ISSUE TITLE
how do i wrap function into wasm memory

### ISSUE THREAD

**Issue by jLn0n** [RealEthanPlayzDev/LuauCeption#1]
i couldn't seem to figure out how to wrap function into wasm memory as it seems like there is no exposed function on wrapping function to the memory

**Comment by RealEthanPlayzDev** [comment]
What do you mean by "wrapping function into wasm memory"? Can you elaborate and tell what are you trying to achieve?

**Comment by jLn0n** [comment]
> What do you mean by "wrapping function into wasm memory"? Can you elaborate and tell what are you trying to achieve?

i want to add a function into the luastate as a new global function, my problem is i dont know how to wrap the function into a wasm-compatible pointer thing

**Comment by jLn0n** [comment]
i figured this out in my mind, but no prototypes for now :(

**Comment by jLn0n** [comment]
i might have to add a new function to FUNC_LIST table then register the functions then blablabla

**Comment by RealEthanPlayzDev** [comment]
I just remembered this issue, since LuauCeption 0.648 theres now a function to insert custom functions to the webassembly using a export (``LuauCeption.wasm.insertCFunction`` if I remember correctly)
