### ISSUE TITLE
Error handling.

### ISSUE THREAD

**Issue by AquaMan4094** [RealEthanPlayzDev/LuauCeption#5]
So I am using this code with Fiu, and in Fiu, it says the provided bytecode is an error message. Now I know this project isnt Fiu, but I'm using the LuauCeption compiler, and I want to catch the error message, because I know in the C++ Luau compiler, you can do `if (bytecode.at(0) == 0) { printf( "%s\n", bytecode.c_str() + 1); }` so how exactly would I mimic that in LuauCeption with the compiler? (I can't find the area where it writes the error message)

P.S if this is a stupid question, I'm sorry.

**Comment by AquaMan4094** [comment]
Oh wait, nevermind, I just fixed it now.

**Comment by RealEthanPlayzDev** [comment]
The check is basically checking if the first character is a null character (0). All error messages start with a null character then the error itself

Since Fiu seems to already do this, you can check their source code and see how to do the check

**Comment by AquaMan4094** [comment]
okk k gotchu
